framework:
    messenger:
        default_bus: event.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
            event.bus:
                default_middleware: allow_no_handlers

        failure_transport: failed

        transports:
            failed: '%env(FAILED_TRANSPORT_DSN)%'

            event:
                dsn: '%env(EVENT_TRANSPORT_DSN)%'
                retry_strategy:
                    delay: 500
                    max_retries: 2
                options:
                    exchange:
                        name: events
                        type: direct
                        default_publish_routing_key: event
                    queues:
                        events:
                            binding_keys: [event]

            synchronize_profile:
                dsn: '%env(SYNCHRONIZE_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                retry_strategy:
                    delay: 500
                    max_retries: 2
                options:
                    exchange:
                        name: synchronize
                        type: direct
                        default_publish_routing_key: synchronize_profile
                    queues:
                        synchronize_market:
                            binding_keys: [synchronize_profile]

            synchronize_email:
                dsn: '%env(SYNCHRONIZE_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                retry_strategy:
                    delay: 500
                    max_retries: 2
                options:
                    exchange:
                        name: synchronize
                        type: direct
                        default_publish_routing_key: synchronize_email
                    queues:
                        synchronize_mess:
                            binding_keys: [synchronize_email]
                        synchronize_market:
                            binding_keys: [synchronize_email]

            synchronize_phone:
                dsn: '%env(SYNCHRONIZE_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                retry_strategy:
                    delay: 500
                    max_retries: 2
                options:
                    exchange:
                        name: synchronize
                        type: direct
                        default_publish_routing_key: synchronize_phone
                    queues:
                        synchronize_mess:
                            binding_keys: [synchronize_phone]
        routing:
            App\Model\User\Event\EditedUserPhoneEvent: synchronize_phone
            App\Model\User\Event\EditedUserEmailEvent: synchronize_email
            App\Model\User\Event\EditedUserProfileEvent: synchronize_profile

            App\Application\Event\User\Registered\RegisteredUserEvent: event
            App\Application\Event\User\RegisteredViaNetwork\RegisteredUserViaNetworkEvent: event
