nelmio_api_doc:
    documentation:
        info:
            title: AuthService Auth
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api/(?!/doc$)
            - ^/open_api/(?!/doc$)
