security:
    encoders:
        App\Infrastructure\User\Security\UserIdentity:
            algorithm: sodium

    providers:
        user_provider:
            id: App\Infrastructure\User\Security\UserProvider

    firewalls:
        api_doc:
            pattern: ^/api/doc
            anonymous:  true

        api_token:
            pattern: ^/api/token$
            security: false

        api:
            pattern: ^/api
            security: true
            stateless: true
            oauth2: true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/doc }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
