imports:
  - { resource: services.yaml }

services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: true

  App\Application\Service\Sms\SmsInterface:
      class: 'App\Application\Service\Sms\FakeSmsService'

  App\Application\Service\User\Network\OAuth\Fetch\FetchUser:
      arguments:
          $clientRegistry: '@App\Application\Service\OAuth\Client\Registry\FakeClientRegistry'
